# Universal Windows Platform
# Build a Universal Windows Platform project using Visual Studio.
# Add steps that test and distribute an app, save build artifacts, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'HyPlayer.sln'
  buildPlatform: 'x64|x86|ARM|ARM64'
  buildConfiguration: 'Release'
  appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages\\'

steps:

- checkout: self
  submodules: true

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DownloadSecureFile@1
  name: signingCert
  displayName: 'Download CA certificate'
  inputs:
    secureFile: 'HyPlayer.pfx'
 
- task: VSBuild@1
  inputs:
    platform: 'x64'
    solution: '$(solution)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:AppxBundlePlatforms="$(buildPlatform)" 
                  /p:AppxPackageDir="$(appxPackageDir)" 
                  /p:AppxBundle=Auto 
                  /p:PackageCertificateThumbprint="" 
                  /p:UapAppxPackageBuildMode=SideloadOnly 
                  /p:AppxPackageSigningEnabled=true 
                  /p:PackageCertificateKeyFile="$(signingCert.secureFilePath)"'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**\bin\$(BuildConfiguration)\**'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.artifactstagingdirectory)/AppxPackages'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(build.artifactstagingdirectory)/drop.zip'
    replaceExistingArchive: true
    verbose: true

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github connection 1'
    repositoryName: 'HyPlayer/HyPlayer'
    action: 'edit'
    target: '$(Build.SourceVersion)'
    tag: 'azure-build'
    title: 'Azure Build on$( Build.BuildNumber)'
    releaseNotesSource: 'inline'
    releaseNotesInline: '> 这是 Azure DevOps 的自动编译,将会在每次Commit之后进行编译. 内容可能稳定,如非特别需要,请使用商店版. 使用此版本出现的问题概不负责'
    assets: '$(Build.ArtifactStagingDirectory)/drop.zip'
    isPreRelease: true
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
